class Mapping:
    INITIAL_PROMPTS = {
        "qudo_borrowing_segmentation": [
            {
                "segment": "Debt-free Borrowers",
                "segment_id": "13237",
                "segmentation": "Borrowing Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Service-led Borrowers",
                "segment_id": "13238",
                "segmentation": "Borrowing Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Struggling Borrowers",
                "segment_id": "13239",
                "segmentation": "Borrowing Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Savvy Borrowers",
                "segment_id": "13240",
                "segmentation": "Borrowing Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Size-matters Borrowers",
                "segment_id": "13241",
                "segmentation": "Borrowing Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Transparency Seekers",
                "segment_id": "13242",
                "segmentation": "Borrowing Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Convenience Seekers",
                "segment_id": "13243",
                "segmentation": "Borrowing Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
        ],
        "qudo_bank_switching_segmentation": [
            {
                "segment": "Lottery Switchers",
                "segment_id": "13244",
                "segmentation": "Bank Switching Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Interest-led Switchers",
                "segment_id": "13245",
                "segmentation": "Bank Switching Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Strongholds",
                "segment_id": "13246",
                "segmentation": "Bank Switching Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Want-it-all Switchers",
                "segment_id": "13247",
                "segmentation": "Bank Switching Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
        ],
        "qudo_financial_attitudes_segmentation": [
            {
                "segment": "Late Majority",
                "segment_id": "13261",
                "segmentation": "Financial Attitudes Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Cautious Online Techies",
                "segment_id": "13262",
                "segmentation": "Financial Attitudes Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Conservative Risk Averse",
                "segment_id": "13263",
                "segmentation": "Financial Attitudes Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Money Centrics",
                "segment_id": "13264",
                "segmentation": "Financial Attitudes Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Money Burners",
                "segment_id": "13265",
                "segmentation": "Financial Attitudes Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Experienced Online Techies",
                "segment_id": "13266",
                "segmentation": "Financial Attitudes Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Conservative Risk Tolerant",
                "segment_id": "13267",
                "segmentation": "Financial Attitudes Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
        ],
        "qudo_financial_behaviour_segmentation": [
            {
                "segment": "Conscious Debtors",
                "segment_id": "13270",
                "segmentation": "Financial Behaviour Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Distressed",
                "segment_id": "13271",
                "segmentation": "Financial Behaviour Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Disciplined Debtors",
                "segment_id": "13272",
                "segmentation": "Financial Behaviour Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Comfortable Savers",
                "segment_id": "13273",
                "segmentation": "Financial Behaviour Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Mainstream",
                "segment_id": "13274",
                "segmentation": "Financial Behaviour Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Debt free Savers",
                "segment_id": "13275",
                "segmentation": "Financial Behaviour Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Retirement Focused",
                "segment_id": "13276",
                "segmentation": "Financial Behaviour Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Dissonant Debtors",
                "segment_id": "13277",
                "segmentation": "Financial Behaviour Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Disciplined & Debt-free",
                "segment_id": "13278",
                "segmentation": "Financial Behaviour Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
        ],
        "qudo_financial_needs_segmentation": [
            {
                "segment": "Debt Fighters",
                "segment_id": "13225",
                "segmentation": "Financial Needs Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "YOLO's",
                "segment_id": "13226",
                "segmentation": "Financial Needs Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Savers",
                "segment_id": "13233",
                "segmentation": "Financial Needs Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Investors",
                "segment_id": "13234",
                "segmentation": "Financial Needs Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Entrepreneuers",
                "segment_id": "13235",
                "segmentation": "Financial Needs Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Future Forward",
                "segment_id": "13236",
                "segmentation": "Financial Needs Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
        ],
        "qudo_fintech_segmentation": [
            {
                "segment": "Peer Focused Mainstream",
                "segment_id": "13287",
                "segmentation": "Fintech Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Risk-averse Late Adopters",
                "segment_id": "13288",
                "segmentation": "Fintech Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Niche Fintech Users",
                "segment_id": "13289",
                "segmentation": "Fintech Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Confident Online Borrowers",
                "segment_id": "13290",
                "segmentation": "Fintech Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Early Adopters",
                "segment_id": "13291",
                "segmentation": "Fintech Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
        ],
        "qudo_panoptic_segmentation": [
            {
                "segment": "Diversifiers",
                "segment_id": "13223",
                "segmentation": "Panoptic Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Alerted",
                "segment_id": "13224",
                "segmentation": "Panoptic Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Meddlers",
                "segment_id": "13227",
                "segmentation": "Panoptic Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Comfortables",
                "segment_id": "13228",
                "segmentation": "Panoptic Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Laggards",
                "segment_id": "13229",
                "segmentation": "Panoptic Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Conservatives",
                "segment_id": "13230",
                "segmentation": "Panoptic Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Risk Dodgers",
                "segment_id": "13231",
                "segmentation": "Panoptic Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Distressed",
                "segment_id": "13232",
                "segmentation": "Panoptic Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
        ],
        "qudo_retail_investors_segmentation": [
            {
                "segment": "Non-Investors",
                "segment_id": "13250",
                "segmentation": "Retail Investors Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Diversifying Investors",
                "segment_id": "13251",
                "segmentation": "Retail Investors Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Equity-focused Investors",
                "segment_id": "13252",
                "segmentation": "Retail Investors Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Novice Investors",
                "segment_id": "13253",
                "segmentation": "Retail Investors Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Ambitious Investors",
                "segment_id": "13254",
                "segmentation": "Retail Investors Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
        ],
        "qudo_savers_segmentation": [
            {
                "segment": "Rainy-day Savers",
                "segment_id": "13255",
                "segmentation": "Savers Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Struggling Savers",
                "segment_id": "13256",
                "segmentation": "Savers Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Disciplined Savers",
                "segment_id": "13257",
                "segmentation": "Savers Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Long-term Savers",
                "segment_id": "13258",
                "segmentation": "Savers Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Holistic Savers",
                "segment_id": "13259",
                "segmentation": "Savers Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
            {
                "segment": "Ambitious Savers",
                "segment_id": "13260",
                "segmentation": "Savers Segmentation",
                "survey": "qudo_financialservices_usa_q1_2023_staging",
                "survey_id": "90525705",
            },
        ],
    }

    INDUSTRY_MAPPING = {
        "tech and comms": "tech",
        "travel and leisure": "trav",
        "food and beverage": "food",
        "trav and leisure": "trav",
        "broadband": "broadband",
        "connectivity": "connectivity",
        "extender": "extender",
        "monitoring": "monitoring",
    }
