version: 0.2
env:
  variables:
    DOCKERFILE: scripts/dockerfile-flask

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 960509716031.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ECR_REPO:latest -f ${DOCKERFILE} .
      - echo
      - docker tag $ECR_REPO:latest $ECR_REPO:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_REPO:latest
      - docker push $ECR_REPO:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"'$ECS_CONTAINER_NAME'","imageUri":"%s"}]' $ECR_REPO:$IMAGE_TAG > imageDefinitions.json
      - cat imageDefinitions.json
artifacts:
    files: imageDefinitions.json